# Generated by Django 3.1 on 2025-04-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_add',
            new_name='date_added',
        ),
    ]
